// <auto-generated />
namespace ShoppingApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class configPage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configPage));
        
        string IMigrationMetadata.Id
        {
            get { return "201910010224442_configPage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
